import type { Person } from '../types';

export const mockPeople: Person[] = [
  {
    "id": '1',
    "parentId": null,
    "spouseId": '2',
    "fullName": "Ahmad bin Sarimon",
    "nickName": "Ahmad",
    "gender": "male",
    "birthDate": "1940-03-15",
    "bio": "Retired soldier",
    "photoUrl": "",
    "status": "active",
  },
  {
    "id": '2',
    "parentId": null,
    "spouseId": '1',
    "fullName": "Jamilah binti Sulaiman",
    "nickName": "Jamilah",
    "gender": "female",
    "birthDate": "1942-07-22",
    "bio": "Retired teacher",
    "photoUrl": "",
    "status": "active"
  },
  {
    "id": '3',
    "parentId": '1',
    "spouseId": '8',
    "fullName": "Hazwan Shafiq bin Ahmad",
    "nickName": "Along",
    "gender": "male",
    "birthDate": "1989-08-29",
    "bio": "Tester",
    "photoUrl": "",
    "status": "active"
  },
  {
    "id": '4',
    "parentId": '1',
    "spouseId": '9',
    "fullName": "Hafizul Asyraf bin Ahmad",
    "nickName": "Angah",
    "gender": "male",
    "birthDate": "1993-10-23",
    "bio": "Programmer",
    "photoUrl": "",
    "status": "active"
  },
  {
    "id": '5',
    "parentId": '1',
    "spouseId": '10',
    "fullName": "Hariz Azrai Adha bin Ahmad",
    "nickName": "Acai",
    "gender": "male",
    "birthDate": "1997-04-18",
    "bio": "Technician",
    "photoUrl": "",
    "status": "active"
  },
  {
    "id": '6',
    "parentId": '1',
    "spouseId": '11',
    "fullName": "Izaura Nur Izatty binti Ahmad",
    "nickName": "Oya",
    "gender": "female",
    "birthDate": "1998-03-31",
    "bio": "Teacher",
    "photoUrl": "",
    "status": "active"
  },
  {
    "id": '7',
    "parentId": '1',
    "spouseId": null,
    "fullName": "Sofea Nur Maisara binti Ahmad",
    "nickName": "Peah",
    "gender": "female",
    "birthDate": "2002-01-09",
    "bio": "Student",
    "photoUrl": "",
    "status": "active"
  },
  {
    "id": '8',
    "parentId": null,
    "spouseId": '3',
    "fullName": "Ili Athirah",
    "nickName": "Ili",
    "gender": "female",
    "birthDate": "1992-05-22",
    "bio": '',
    "photoUrl": "",
    "status": "active"
  },
  {
    "id": '9',
    "parentId": null,
    "spouseId": '4',
    "fullName": "Nurul Azani binti Azman",
    "nickName": "Zani",
    "gender": "female",
    "birthDate": "1993-09-26",
    "bio": '',
    "photoUrl": "",
    "status": "active"
  },
  {
    "id": '10',
    "parentId": null,
    "spouseId": '5',
    "fullName": "Nurul Aina",
    "nickName": "Aina",
    "gender": "female",
    "birthDate": "1997-05-10",
    "bio": '',
    "photoUrl": "",
    "status": "active"
  },
  {
    "id": '11',
    "parentId": null,
    "spouseId": '6',
    "fullName": "Muhammad Hariz Azizi",
    "nickName": "GG",
    "gender": "male",
    "birthDate": "1999-01-23",
    "bio": '',
    "photoUrl": "",
    "status": "active"
  }
];
