import type { Person } from '../types';

export const mockPeople: Person[] = [
  // Generation 1: Grandparents
  {
    id: '1',
    parentId: null,
    spouseId: '2',
    fullName: 'Ahmad bin Sarimon',
    nickName: 'Pak Ahmad',
    gender: 'male',
    birthDate: '1940-03-15',
    bio: 'Patriarch of the family, retired government officer.',
    photoUrl: 'https://via.placeholder.com/150',
    status: 'active',
  },
  {
    id: '2',
    parentId: null,
    spouseId: '1',
    fullName: 'Jamilah binti Sulaiman',
    nickName: 'Mak Jamilah',
    gender: 'female',
    birthDate: '1942-07-22',
    bio: 'Matriarch of the family, homemaker and community leader.',
    photoUrl: 'https://via.placeholder.com/150',
    status: 'active',
  },

  // Generation 2: Parents
  {
    id: '3',
    parentId: '1',
    spouseId: '4',
    fullName: 'Hassan bin Ahmad',
    nickName: 'Abang Hassan',
    gender: 'male',
    birthDate: '1965-05-10',
    bio: 'Eldest son, successful entrepreneur.',
    photoUrl: 'https://via.placeholder.com/150',
    status: 'active',
  },
  {
    id: '4',
    parentId: null,
    spouseId: '3',
    fullName: 'Siti Aminah binti Rahman',
    nickName: 'Kak Aminah',
    gender: 'female',
    birthDate: '1967-11-18',
    bio: 'Teacher and devoted mother.',
    photoUrl: 'https://via.placeholder.com/150',
    status: 'active',
  },
  {
    id: '5',
    parentId: '1',
    spouseId: '6',
    fullName: 'Ibrahim bin Ahmad',
    nickName: 'Pak Ibrahim',
    gender: 'male',
    birthDate: '1968-09-25',
    bio: 'Second son, doctor at local hospital.',
    photoUrl: 'https://via.placeholder.com/150',
    status: 'active',
  },
  {
    id: '6',
    parentId: null,
    spouseId: '5',
    fullName: 'Noraini binti Abdullah',
    nickName: 'Kak Noraini',
    gender: 'female',
    birthDate: '1970-02-14',
    bio: 'Nurse and health advocate.',
    photoUrl: 'https://via.placeholder.com/150',
    status: 'active',
  },
  {
    id: '7',
    parentId: '1',
    fullName: 'Zainab binti Ahmad',
    nickName: 'Kak Zainab',
    gender: 'female',
    birthDate: '1972-06-08',
    bio: 'Youngest daughter, university lecturer.',
    photoUrl: 'https://via.placeholder.com/150',
    status: 'active',
  },

  // Generation 3: Children
  {
    id: '8',
    parentId: '3',
    spouseId: '9',
    fullName: 'Azman bin Hassan',
    nickName: 'Man',
    gender: 'male',
    birthDate: '1990-03-12',
    bio: 'Software engineer.',
    photoUrl: 'https://via.placeholder.com/150',
    status: 'active',
  },
  {
    id: '9',
    parentId: null,
    spouseId: '8',
    fullName: 'Nurul Huda binti Ismail',
    nickName: 'Huda',
    gender: 'female',
    birthDate: '1992-08-20',
    bio: 'Graphic designer.',
    photoUrl: 'https://via.placeholder.com/150',
    status: 'active',
  },
  {
    id: '10',
    parentId: '3',
    spouseId: '11',
    fullName: 'Farah binti Hassan',
    nickName: 'Farah',
    gender: 'female',
    birthDate: '1993-11-05',
    bio: 'Accountant.',
    photoUrl: 'https://via.placeholder.com/150',
    status: 'active',
  },
  {
    id: '11',
    parentId: null,
    spouseId: '10',
    fullName: 'Rizal bin Mahmud',
    nickName: 'Rizal',
    gender: 'male',
    birthDate: '1991-04-17',
    bio: 'Civil engineer.',
    photoUrl: 'https://via.placeholder.com/150',
    status: 'active',
  },
  {
    id: '12',
    parentId: '5',
    spouseId: '13',
    fullName: 'Hafiz bin Ibrahim',
    nickName: 'Hafiz',
    gender: 'male',
    birthDate: '1995-07-22',
    bio: 'Medical resident.',
    photoUrl: 'https://via.placeholder.com/150',
    status: 'active',
  },
  {
    id: '13',
    parentId: null,
    spouseId: '12',
    fullName: 'Aisyah binti Karim',
    nickName: 'Aisyah',
    gender: 'female',
    birthDate: '1996-12-10',
    bio: 'Pharmacist.',
    photoUrl: 'https://via.placeholder.com/150',
    status: 'active',
  },
  {
    id: '14',
    parentId: '5',
    fullName: 'Amira binti Ibrahim',
    nickName: 'Amira',
    gender: 'female',
    birthDate: '1998-05-16',
    bio: 'Law student.',
    photoUrl: 'https://via.placeholder.com/150',
    status: 'active',
  },
  {
    id: '15',
    parentId: '5',
    fullName: 'Danial bin Ibrahim',
    nickName: 'Dan',
    gender: 'male',
    birthDate: '2000-09-30',
    bio: 'Engineering student.',
    photoUrl: 'https://via.placeholder.com/150',
    status: 'active',
  },

  // Generation 4: Grandchildren
  {
    id: '16',
    parentId: '8',
    fullName: 'Irfan bin Azman',
    nickName: 'Irfan',
    gender: 'male',
    birthDate: '2015-02-14',
    bio: 'Primary school student.',
    photoUrl: 'https://via.placeholder.com/150',
    status: 'active',
  },
  {
    id: '17',
    parentId: '8',
    fullName: 'Sofia binti Azman',
    nickName: 'Sofia',
    gender: 'female',
    birthDate: '2017-06-20',
    bio: 'Kindergarten student.',
    photoUrl: 'https://via.placeholder.com/150',
    status: 'active',
  },
  {
    id: '18',
    parentId: '10',
    fullName: 'Aishah binti Rizal',
    nickName: 'Aishah',
    gender: 'female',
    birthDate: '2016-04-08',
    bio: 'Primary school student.',
    photoUrl: 'https://via.placeholder.com/150',
    status: 'active',
  },
  {
    id: '19',
    parentId: '10',
    fullName: 'Luqman bin Rizal',
    nickName: 'Luqman',
    gender: 'male',
    birthDate: '2018-11-25',
    bio: 'Kindergarten student.',
    photoUrl: 'https://via.placeholder.com/150',
    status: 'active',
  },
  {
    id: '20',
    parentId: '10',
    fullName: 'Zara binti Rizal',
    nickName: 'Zara',
    gender: 'female',
    birthDate: '2020-03-12',
    bio: 'Preschooler.',
    photoUrl: 'https://via.placeholder.com/150',
    status: 'active',
  },
  {
    id: '21',
    parentId: '12',
    fullName: 'Adam bin Hafiz',
    nickName: 'Adam',
    gender: 'male',
    birthDate: '2019-07-19',
    bio: 'Toddler.',
    photoUrl: 'https://via.placeholder.com/150',
    status: 'active',
  },
  {
    id: '22',
    parentId: '12',
    fullName: 'Maryam binti Hafiz',
    nickName: 'Maryam',
    gender: 'female',
    birthDate: '2021-10-05',
    bio: 'Toddler.',
    photoUrl: 'https://via.placeholder.com/150',
    status: 'active',
  },

  // Generation 5: Great-grandchildren  
  {
    id: '23',
    parentId: '16',
    fullName: 'Aqil bin Irfan',
    nickName: 'Aqil',
    gender: 'male',
    birthDate: '2023-01-20',
    bio: 'Infant.',
    photoUrl: 'https://via.placeholder.com/150',
    status: 'active',
  },
];
